# Generated by Django 2.1.2 on 2018-10-28 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GPIOPin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pin', models.IntegerField()),
                ('mode', models.CharField(choices=[('BOARD', 'BOARD'), ('BCM', 'BCM')], default='BOARD', max_length=10)),
                ('setup', models.CharField(choices=[('IN', 'IN'), ('OUT', 'OUT')], default='IN', max_length=10)),
                ('status', models.CharField(choices=[('HIGH', 'HIGH'), ('LOW', 'LOW')], default='LOW', max_length=10)),
            ],
        ),
    ]
