# Generated by Django 2.1.2 on 2018-10-29 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_gpiopin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shutter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.IntegerField()),
                ('mode', models.CharField(choices=[('IDLE', 'IDLE'), ('GOINGUP', 'GOINGUP'), ('GOINGDOWN', 'GOINGDOWN')], default='IDLE', max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='gpiopin',
            name='setup',
            field=models.CharField(choices=[('IN', 'IN'), ('OUT', 'OUT')], default='OUT', max_length=10),
        ),
        migrations.AddField(
            model_name='shutter',
            name='gpiopin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.GPIOPin'),
        ),
    ]
