# Generated by Django 2.1.2 on 2018-11-01 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20181029_1636'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('timetoexecute', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='shutter',
            name='timetoopen',
            field=models.IntegerField(blank=True, default=30, null=True),
        ),
        migrations.AlterField(
            model_name='shutter',
            name='mode',
            field=models.CharField(choices=[('IDLE', 'IDLE'), ('GOINGUP', 'GOINGUP'), ('GOINGDOWN', 'GOINGDOWN'), ('MANUAL', 'MANUAL')], default='IDLE', max_length=10),
        ),
        migrations.AlterField(
            model_name='shutter',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shutter',
            name='currentjob',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Job'),
        ),
    ]
