# Generated by Django 2.1.2 on 2018-11-02 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20181101_1759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shutter',
            name='gpiopin',
        ),
        migrations.AddField(
            model_name='shutter',
            name='gpiopindown',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='app.GPIOPin'),
        ),
        migrations.AddField(
            model_name='shutter',
            name='gpiopinup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='app.GPIOPin'),
        ),
        migrations.AlterField(
            model_name='gpiopin',
            name='mode',
            field=models.CharField(choices=[('BOARD', 'BOARD'), ('BCM', 'BCM')], default='BCM', max_length=10),
        ),
        migrations.AlterField(
            model_name='gpiopin',
            name='status',
            field=models.CharField(choices=[('HIGH', 'HIGH'), ('LOW', 'LOW')], default='HIGH', max_length=10),
        ),
    ]
