# Generated by Django 2.1.2 on 2018-11-02 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20181102_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='shutter',
            name='faicon',
            field=models.CharField(blank=True, default='bars', max_length=100, null=True),
        ),
    ]
